fix(content): [Angular] Change the id_token result title
asgardeo/asgardeo-auth-angular-sdk pull request #71
Opened 2021-03-05 15:25 UTC by yasinmiran

## Purpose
> Please note the $subject

## Changes
- Alter the `id_token` content section title. This PR aims to add changes made in https://github.com/asgardeo/asgardeo-auth-react-sdk/pull/20 to Angular samples.

2021-03-08 04:50 UTC, JanithGan requested changes

2021-03-08 04:50 UTC, JanithGan commented on samples/asgardeo-angular-app/src/app/app.component.html
> +                      <a href="https://www.npmjs.com/package/@asgardeo/auth-react/v/latest" target="_blank">
```suggestion
                      <a href="https://www.npmjs.com/package/@asgardeo/auth-angular/v/latest" target="_blank">
```

2021-03-08 04:50 UTC, JanithGan commented on samples/asgardeo-angular-app/src/app/app.component.html
> +                        @asgardeo/auth-react
```suggestion
                        @asgardeo/auth-angular
```

2021-03-08 04:50 UTC, JanithGan commented on samples/asgardeo-angular-app-with-router/src/app/profile/profile.component.html
> +                <a href="https://www.npmjs.com/package/@asgardeo/auth-react/v/latest" target="_blank">
```suggestion
                <a href="https://www.npmjs.com/package/@asgardeo/auth-angular/v/latest" target="_blank">
```

2021-03-08 04:50 UTC, JanithGan commented on samples/asgardeo-angular-app-with-router/src/app/profile/profile.component.html
> +                    @asgardeo/auth-react
```suggestion
                    @asgardeo/auth-angular
```

2021-03-08 04:58 UTC, yasinmiran commented on samples/asgardeo-angular-app/src/app/app.component.html
> +                      <a href="https://www.npmjs.com/package/@asgardeo/auth-react/v/latest" target="_blank">
Resolved this content error in commit 86cd42f.

2021-03-08 04:58 UTC, yasinmiran commented on samples/asgardeo-angular-app/src/app/app.component.html
> +                        @asgardeo/auth-react
Resolved this content error in commit 86cd42f.

2021-03-08 04:59 UTC, yasinmiran commented on samples/asgardeo-angular-app-with-router/src/app/profile/profile.component.html
> +                <a href="https://www.npmjs.com/package/@asgardeo/auth-react/v/latest" target="_blank">
Resolved this content error in commit 86cd42f.

2021-03-08 04:59 UTC, yasinmiran commented on samples/asgardeo-angular-app-with-router/src/app/profile/profile.component.html
> +                    @asgardeo/auth-react
Resolved this content error in commit 86cd42f.

2021-03-08 11:48 UTC, JanithGan approved these changes

2021-03-15 10:21 UTC, thivi approved these changes

2021-03-15 10:23 UTC, merged